name: BanManagement
version: 1.0
main: me.pogostick29dev.banmanagement.BanManagement
author: PogoStick29Dev
description: Ban people from your server. Also has a web frontend.

commands:
  ban:
    usage: /<command> <player> <message>
    description: Ban a player.

  unban:
    usage: /<command> <player>
    description: Unban a player.

  checkban:
    usage: /<command> <player>
    description: Check the information of a ban.